In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv('C:/Users/sai kiran/Downloads/loan_final313 - Copy.csv')
data.head()

id  year     issue_d  final_d  emp_length_int home_ownership  \
0  1077501  2011  01/12/2011  1012015            10.0           RENT   
1  1077430  2011  01/12/2011  1042013             0.5           RENT   
2  1077175  2011  01/12/2011  1062014            10.0           RENT   
3  1076863  2011  01/12/2011  1012015            10.0           RENT   
4  1075358  2011  01/12/2011  1012016             1.0           RENT   

   home_ownership_cat income_category  annual_inc  income_cat    ...     \
0                   1             Low       24000           1    ...      
1                   1             Low       30000           1    ...      
2                   1             Low       12252           1    ...      
3                   1             Low       49200           1    ...      
4                   1             Low       80000           1    ...      

   loan_condition_cat interest_rate  grade grade_cat    dti   total_pymnt  \
0                   0         10.65      B         2  27.65   5861.071414   
1                   1         15.27      C         3   1.00   1008.710000   
2                   0         15.96      C         3   8.72   3003.653644   
3                   0         13.49      C         3  20.00  12226.302210   
4                   0         12.69      B         2  17.94   3242.170000   

   total_rec_prncp recoveries  installment    region  
0          5000.00       0.00       162.87   munster  
1           456.46     117.08        59.83  leinster  
2          2400.00       0.00        84.33  cannught  
3         10000.00       0.00       339.31    ulster  
4          2233.10       0.00        67.79    ulster  

[5 rows x 30 columns]

## Feature Elimination
### will remove all redundant features as both the columns such as 'home_ownership' and 'home_ownership_cat' mean the same
### will remove features such as ''application_type_cat'' as they doesn't impact the target class (from visualisation)

In [3]:
data.drop(['id','home_ownership','income_category','loan_condition_cat','annual_inc','term','application_type','purpose','interest_payments','grade','dti','application_type_cat','recoveries'],axis=1,inplace=True)
data.head()

year     issue_d  final_d  emp_length_int  home_ownership_cat  income_cat  \
0  2011  01/12/2011  1012015            10.0                   1           1   
1  2011  01/12/2011  1042013             0.5                   1           1   
2  2011  01/12/2011  1062014            10.0                   1           1   
3  2011  01/12/2011  1012015            10.0                   1           1   
4  2011  01/12/2011  1012016             1.0                   1           1   

   loan_amount  term_cat  purpose_cat  interest_payment_cat loan_condition  \
0         5000         1            1                     1      Good Loan   
1         2500         2            2                     2       Bad Loan   
2         2400         1            3                     2      Good Loan   
3        10000         1            4                     2      Good Loan   
4         3000         2            4                     1      Good Loan   

   interest_rate  grade_cat   total_pymnt  total_rec_prncp  installment  \
0          10.65          2   5861.071414          5000.00       162.87   
1          15.27          3   1008.710000           456.46        59.83   
2          15.96          3   3003.653644          2400.00        84.33   
3          13.49          3  12226.302210         10000.00       339.31   
4          12.69          2   3242.170000          2233.10        67.79   

     region  
0   munster  
1  leinster  
2  cannught  
3    ulster  
4    ulster

### Handling categorical values

In [4]:
data['region'].value_counts()

leinster        214646
ulster          208731
Northern-Irl    204399
cannught        155029
munster         104574
Name: region, dtype: int64

In [5]:
data['region'].replace('leinster',0,inplace=True)
data['region'].replace('ulster',1,inplace=True)
data['region'].replace('Northern-Irl',2,inplace=True)
data['region'].replace('cannught',3,inplace=True)
data['region'].replace('munster',4,inplace=True)

In [6]:
data['region'].value_counts()

0    214646
1    208731
2    204399
3    155029
4    104574
Name: region, dtype: int64

In [7]:
data['year'].value_counts()

2015    421094
2014    235628
2013    134755
2012     53367
2011     21721
2010     12537
2009      5281
2008      2393
2007       603
Name: year, dtype: int64

In [8]:
### Creating New Features  length=issue_d - final_d

In [9]:
data.drop(['issue_d','final_d'],axis=1,inplace=True)

### Applying Binning to Numerical features (from visualisation) 

In [10]:
bins=[0,2,8,11]
labels=[0,1,2]
data['emp_length_int']=pd.cut(data['emp_length_int'],bins=bins,labels=labels)

In [11]:
data['emp_length_int'].value_counts()

1    354583
2    326226
0    206570
Name: emp_length_int, dtype: int64

In [12]:
bins=[0,5000,20000,35000]
labels=[0,1,2]
data['loan_amount']=pd.cut(data['loan_amount'],bins=bins,labels=labels)

In [13]:
data['loan_amount'].value_counts()

1    583862
2    200837
0    102680
Name: loan_amount, dtype: int64

In [14]:
bins=[0,5,10,15,20,25,30]
labels=[0,1,2,3,4,5]
data['interest_rate']=pd.cut(data['interest_rate'],bins=bins,labels=labels)

In [15]:
data['interest_rate'].value_counts()

2    372060
1    235621
3    221068
4     52137
5      6493
0         0
Name: interest_rate, dtype: int64

In [16]:
bins=[0,5000,10000,15000,20000,30000,50000]
labels=[0,1,2,3,4,5]
data['total_pymnt']=pd.cut(data['total_pymnt'],bins=bins,labels=labels)

In [17]:
data['total_pymnt'].value_counts()

0    431628
1    198680
2    108090
3     57818
4     52370
5     20816
Name: total_pymnt, dtype: int64

In [18]:
bins=[0,2500,5000,10000,15000,35000]
labels=[0,1,2,3,4]
data['total_rec_prncp']=pd.cut(data['total_rec_prncp'],bins=bins,labels=labels)

In [19]:
data['total_rec_prncp'].value_counts()

0    362111
1    177233
2    170898
4     82289
3     76668
Name: total_rec_prncp, dtype: int64

In [20]:
bins=[0,300,600,800,1200,1400]
labels=[0,1,2,3,4]
data['installment']=pd.cut(data['installment'],bins=bins,labels=labels)

In [21]:
data['installment'].value_counts()

1    397791
0    288874
2    120875
3     73014
4      6790
Name: installment, dtype: int64

In [22]:
data.head()

year emp_length_int  home_ownership_cat  income_cat loan_amount  term_cat  \
0  2011              2                   1           1           0         1   
1  2011              0                   1           1           0         2   
2  2011              2                   1           1           0         1   
3  2011              2                   1           1           1         1   
4  2011              0                   1           1           0         2   

   purpose_cat  interest_payment_cat loan_condition interest_rate  grade_cat  \
0            1                     1      Good Loan             2          2   
1            2                     2       Bad Loan             3          3   
2            3                     2      Good Loan             3          3   
3            4                     2      Good Loan             2          3   
4            4                     1      Good Loan             2          2   

  total_pymnt total_rec_prncp installment  region  
0           1               1           0       4  
1           0               0           0       0  
2           0               0           0       3  
3           2               2           1       1  
4           0               0           0       1

### Label Encoder

In [23]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data['year']=l.fit_transform(data['year'])
l=LabelEncoder()
data['loan_condition']=l.fit_transform(data['loan_condition'])

### Algorithemic Part

In [24]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression,Perceptron
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
data=data.dropna()
data.to_csv (r'C:/Users/sai kiran/Desktop/export_dataframe.csv', index = False, header=True)
y=data['loan_condition'].values
data.drop('loan_condition',axis=1,inplace=True)
x=data[:].values
y=y.reshape(-1, 1)
x_train,x_test,y_train,y_test = train_test_split(x,y)

C:\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [25]:
print(x,y)
print(x.shape,y.shape)

[[4 2 1 ... 1 0 4]
 [4 0 1 ... 0 0 0]
 [4 2 1 ... 0 0 3]
 ...
 [8 1 1 ... 0 1 0]
 [8 0 1 ... 0 1 2]
 [8 2 1 ... 2 2 0]] [[1]
 [0]
 [1]
 ...
 [1]
 [1]
 [1]]
(868946, 14) (868946, 1)


In [28]:
logistic=LogisticRegression()
forest=RandomForestClassifier
logistic.fit(x_train,y_train)
pred=logistic.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)
precision_recall_fscore_support(y_test, pred, average='macro')

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9290728559131272


(0.7972595812843413, 0.5622261654122253, 0.5900031998094473, None)

### Decision Tree

In [27]:
from sklearn import tree
from sklearn.metrics import precision_recall_fscore_support
clf = tree.DecisionTreeClassifier()
clf.fit(x_train,y_train)
pred=clf.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)
precision_recall_fscore_support(y_test, pred, average='macro')

0.934965038184103


(0.7742881993578441, 0.7131046183259986, 0.7388918870610781, None)

### Naive Bayes

In [29]:
from sklearn.naive_bayes import GaussianNB
clf= GaussianNB()
clf.fit(x_train,y_train)
pred=clf.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)
precision_recall_fscore_support(y_test, pred, average='macro')

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.8920809990931563


(0.6019727804619517, 0.5931937293439398, 0.5972752226412767, None)

### SVM

In [30]:
#from sklearn import svm
#clf = svm.SVC()
#clf.fit(x_train,y_train)
#pred=clf.predict(x_test)
#print(accuracy_score(pred,y_test))
#confusion_matrix(pred,y_test)
#precision_recall_fscore_support(y_test, pred, average='macro')

### Random Forest

In [31]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=8, random_state=0)
clf.fit(x_train,y_train)
pred=clf.predict(x_test)
print(accuracy_score(pred,y_test))
confusion_matrix(pred,y_test)
precision_recall_fscore_support(y_test, pred, average='macro')

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


0.9343712166896063


(0.9456004135305681, 0.5695568932180537, 0.6046989389904954, None)

# ANN

In [34]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(16, input_dim=14, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train,y_train, epochs=80, batch_size=30)

Epoch 1/80
651709/651709 [==============================] - 33s 50us/step - loss: 0.2032 - acc: 0.9329
Epoch 2/80
651709/651709 [==============================] - 28s 43us/step - loss: 0.1817 - acc: 0.9420
Epoch 3/80
651709/651709 [==============================] - 27s 42us/step - loss: 0.1770 - acc: 0.9442
Epoch 4/80
651709/651709 [==============================] - 30s 46us/step - loss: 0.1747 - acc: 0.9450
Epoch 5/80
651709/651709 [==============================] - 28s 42us/step - loss: 0.1727 - acc: 0.9459
Epoch 6/80
651709/651709 [==============================] - 26s 39us/step - loss: 0.1716 - acc: 0.9463
Epoch 7/80
651709/651709 [==============================] - 31s 47us/step - loss: 0.1703 - acc: 0.9470
Epoch 8/80
651709/651709 [==============================] - 33s 51us/step - loss: 0.1696 - acc: 0.9472
Epoch 9/80
651709/651709 [==============================] - 35s 53us/step - loss: 0.1689 - acc: 0.9476
Epoch 10/80
651709/651709 [==============================] - 34s 52us/ste

651709/651709 [==============================] - 28s 44us/step - loss: 0.1637 - acc: 0.9497 0s - loss: 0.1638 - acc
Epoch 76/80
651709/651709 [==============================] - 25s 38us/step - loss: 0.1635 - acc: 0.9496
Epoch 77/80
651709/651709 [==============================] - 26s 40us/step - loss: 0.1636 - acc: 0.9496
Epoch 78/80
651709/651709 [==============================] - 26s 40us/step - loss: 0.1636 - acc: 0.9497
Epoch 79/80
651709/651709 [==============================] - 26s 40us/step - loss: 0.1636 - acc: 0.9497
Epoch 80/80
651709/651709 [==============================] - 28s 43us/step - loss: 0.1635 - acc: 0.9496


In [36]:
_,accuracy = model.evaluate(x_test,y_test)

217237/217237 [==============================] - 4s 18us/step


In [38]:
pred=model.predict_classes(x_test)

In [40]:
precision_recall_fscore_support(y_test, pred, average='macro')

(0.9158501216189137, 0.6992847679769196, 0.7632557693463329, None)